spring.application.name=oldtown-pharma-api

security.jwt.secret=troque-esta-chave-por-uma-bem-grande-e-segura-123456789
security.jwt.access-token-expiration-minutes=15
security.jwt.refresh-token-expiration-days=7